dist: focal
arch:
  - amd64
  - ppc64le
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"  # development branch
  - "3.12-dev"
  - "pypy3.9-7.3.9"
jobs:
 exclude:
  - arch: ppc64le
    python: "pypy3.9-7.3.9"

allow_failures:
    - python: "3.12-dev"

install:
  # TODO: Remove tox limitation when https://github.com/tox-dev/tox-travis/pull/160
  - pip install coveralls tox-travis importlib_metadata 'tox<4'
script:
  tox
after_success:
  coveralls
