# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

version: 1.2.14.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python37-x64"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python38"
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python38-x64"
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python39"
      TOX_ENV: "py39"

    - PYTHON: "C:\\Python39-x64"
      TOX_ENV: "py39"

    - PYTHON: "C:\\Python310"
      TOX_ENV: "py310"

    - PYTHON: "C:\\Python310-x64"
      TOX_ENV: "py310"

    - PYTHON: "C:\\Python311"
      TOX_ENV: "py311"

    - PYTHON: "C:\\Python311-x64"
      TOX_ENV: "py311"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;C:\MinGW\msys\1.0\bin;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%\\python.exe -V"
  - "%PYTHON%\\python.exe -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install tox"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%\\Scripts\\tox.exe -e %TOX_ENV%"

after_test:
  - "%PYTHON%\\python.exe setup.py --command-packages wheel bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
